name: Build EnxyWidgets

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'  
    - uses: microsoft/setup-msbuild@v2

    - uses: lukka/get-cmake@latest

    - name: Setup local vcpkg  
      shell: cmd  
      run: |  
        git clone https://github.com/microsoft/vcpkg.git  
        .\vcpkg\bootstrap-vcpkg.bat     
    # CACHE
    - name: Cache vcpkg
      uses: actions/cache@v4
      with:
        path: |
          build
          vcpkg_installed
          C:/vcpkg/packages
          C:/vcpkg/downloads
          C:/vcpkg/buildtrees
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}

    - name: Build  
      shell: cmd  
      run: |  
        :: Build  
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=x64
        cmake -B build -S . -A X64 ^  
        -DCMAKE_BUILD_TYPE=Release ^  
        -DCommonLibSSE_DIR=D:/a/EnxyWidget2/EnxyWidget2/external/CommonLibSSE-NG/cmake ^  
        -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake  
        cmake --build build --config Release    
    - name: Upload DLL
      uses: actions/upload-artifact@v4
      with:
        name: EnxyAbilities
        path: build/**/*.dll
